[build-system]
requires = ["setuptools>=61.8", "wheel", "Cython>=0.29"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["caqui*"]
exclude = ["tests*", "utils", ".vscode", ".git*", "dist"]

[project]
name = "caqui"
version = "5.0.0"
authors = [
  { name="Douglas Cardoso", email="noemail@noemail.com" },
]
description = "Run asynchronous commands in WebDrivers"
keywords = ["automation", "asynchronous", "test", "crawler", "robotic process automation", "rpa"]
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
[project.license]
"file" = "LICENSE"

dependencies = [
  "requests",
  "aiohttp",
  "webdriver_manager",
  "types-requests",
  "orjson",
  "Cython",
  "beautifulsoup4",
  "git+https://github.com/HyperionGray/python-chrome-devtools-protocol.git@5915dce242d4f0cd8c5f8a5e843a535dacc57fc3"
]

[project.urls]
"Homepage" = "https://github.com/douglasdcm/caqui"
"Bug Tracker" = "https://github.com/douglasdcm/caqui/issues"
