[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "caqui"
version = "5.0.0rc2"
description = "Run asynchronous commands in WebDrivers"
readme = "README.md"
requires-python = ">=3.7"

authors = [
  { name="Douglas Cardoso", email="noemail@noemail.com" }
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
  "requests",
  "aiohttp",
  "webdriver_manager",
  "types-requests",
  "beautifulsoup4",
  "chrome-devtools-protocol>=0.5.1rc0"
]

license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/douglasdcm/caqui"
"Bug Tracker" = "https://github.com/douglasdcm/caqui/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["caqui*"]
