[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools.packages.find]
include = ["caqui*"]
exclude = ["tests*", "utils", ".vscode", ".git*", "dist"]

[project]
name = "caqui"
version = "4.0.0"
author = "Douglas Cardoso"
description = "Run asynchronous commands in WebDrivers"
keywords = ["automation", "asynchronous", "test", "crawler", "robotic process automation", "rpa"]
readme = "README.md"
requires-python = ">=3.7"
classifiers = 
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",

install_requires = 
  "requests",
  "aiohttp",
  "webdriver_manager",
  "types-requests",
  "orjson",

[project.urls]
"Homepage" = "https://github.com/douglasdcm/caqui"
"Bug Tracker" = "https://github.com/douglasdcm/caqui/issues"

[tool.mypy]
exclude=["tests/performance/test_process_data.py", "tests/test_sniffer.py"]
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = false
disallow_any_generics = false
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_untyped_defs=false
check_untyped_defs = true
