# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
requires = virtualenv<20.22.0
envlist = py{36,37,38,39,310,311,312}, linter

[testenv]
deps =
    -r test-requirements.txt
    -r dev-requirements.txt
commands =
    pytest {posargs}

[testenv:linter]
deps = 
    black
    flake8
    mypy
    isort
commands = 
    ;black -l 100 .
    isort --profile black --line-length 100 caqui tests
    flake8 --exclude venv*,.tox --max-line-length 100
    mypy caqui tests --config=setup.cfg
